---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcd.dilshan.com
  resources:
  - etcdconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.dilshan.com
  resources:
  - etcdconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - etcd.dilshan.com
  resources:
  - etcdconfigs/status
  verbs:
  - get
  - patch
  - update
